# Generated by Django 2.0 on 2018-04-05 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20180405_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringpattern',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_pattern', to='tasks.Task'),
        ),
    ]
