# Generated by Django 2.0 on 2018-04-05 13:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_taskrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
