# Generated by Django 2.0 on 2018-04-15 19:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_userprofileinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskrecord',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 15, 19, 34, 45, 590881, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='taskrecord',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 15, 19, 34, 45, 697902, tzinfo=utc)),
        ),
    ]
