# Generated by Django 2.0 on 2018-04-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20180416_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='taskrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
