# Generated by Django 2.0 on 2018-04-21 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_auto_20180416_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrecord',
            name='record_date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 4, 21, 16, 43, 47, 147858)),
            preserve_default=False,
        ),
    ]
